---
- name: Remove i386 architecture 
  command: dpkg --remove-architecture i386

# TODO(enolfc): fix this!
- name: Install UI with usual script
  shell: |
    curl -L https://raw.githubusercontent.com/EGI-FCTF/fedcloud-userinterface/master/fedcloud-ui.sh > /tmp/fedcloud.sh
    cat /tmp/fedcloud.ui | bash -
    rm -rf /tmp/fedcloud.ui

- name: install extra packages
  apt:
    name: ["ntp", "dkms"]
    state: present
    update_cache: yes
 
- name: enable ntp
  service:
    name: ntp
    enabled: yes

- name: install virtualbox additions
  shell: |
    vbox_latest=$(curl http://download.virtualbox.org/virtualbox/LATEST.TXT)
    curl http://download.virtualbox.org/virtualbox/$vbox_latest/VBoxGuestAdditions_$vbox_latest.iso > /tmp/vbox.iso
    mount -o loop,ro /tmp/vbox.iso /mnt
    pushd /mnt
    ./VBoxLinuxAdditions.run || true
    popd
    umount /mnt
    rm -rf /tmp/vbox.iso

- name: Make sure that ubuntu user password will expire when created with cloud-init
  copy:
    src: 02_fedcloud_expire_password.cfg
    dest: /etc/cloud/cloud.cfg.d/02_fedcloud_expire_password.cfg

- name: install development environment
  apt:
    name: ["vim", "git", "openjdk-8-jre", "openjdk-8-jdk", "maven", "python-pip", "python-dev", "libffi-dev", "libssl-dev", "python-keystoneclient", "python-openstackclient"]
    state: present
    update_cache: yes

# TODO(enolfc): use systemd?
- name: Add fetch-crl to rc.local 
  copy:
    src: rc.local
    dest: /etc/rc.local 
