- hosts: all
  gather_facts: False
  tasks:
  - name: install python
    raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal)

- hosts: all
  tasks:
  - name: update packages
    apt: upgrade=dist
